### 线性代数基础

#### Scalars(标量), Vectors(向量), Matrices(矩阵) and Tensors(张量)

*  <b>Scalars</b>: A scalar is just a single number, in contrast to most of the other objects studied in linear algebra, which are usually arrays of multiple numbers.We write scalars in italics. We usually give scalars lowercase variable names.When we introduce them, we specify what kind of number they are. For29
   CHAPTER 2. LINEAR ALGEBRA example, we might say “Let s ∈ R be the slope of the line,” while defining areal-valued scalar, or “Let n ∈ N be the number of units,” while defining anatural number scalar.
   * 标量: 和大多数其他科学相反, 在线代中, 一个标量就单单代表一个数字, 她既不是一个数组也不带有其他的结构; 
* <b>Vectors</b>: A vector is an array of numbers. The numbers are arranged in order. We can identify each individual number by its index in that ordering.Typically we give vectors lowercase names in bold typeface, such asx. Theelements of the vector are identified by writing its name in italic typeface,with a subscript. The first element ofxisx1, the second element isx2, andso on. We also need to say what kind of numbers are stored in the vector. Ifeach element is inR, and the vector hasnelements, then the vector lies inthe set formed by taking the Cartesian product ofR ntimes, denoted asRn.When we need to explicitly identify the elements of a vector, we write themas a column enclosed in square brackets:
    * 向量: 一个向量就是一个数组, 数组有序排列; 我们可以通过索引, 来获取对应的值;
    ```
    import numpy as np
    a = np.random.rand(1, 5)
    ```
* <b>Matrices</b>:  Matrices: A matrix is a 2-D array of numbers, so each element is identifiedby two indices instead of just one.
    * 矩阵: 一个矩阵就是一个2维数字组合, 所以每一个元素我们可以同个两个索引值(对应的行列)来找到对应的值
    
* <b>Tensors</b>: In some cases we will need an array with more than two axes.In the general case, an array of numbers arranged on a regular grid with avariable number of axes is known as a tensor. We denote a tensor named “A” with this type face:A. We identify the element of A at coordinates (i, j, k)by writing Ai,j,k.
    * 张量: 在某些情况下,我们一个需要的不仅仅是两个方向的数组; 在通常情况下, 布置在具有可变轴数的规则网格上的数字阵列被称为张量;我们用这种类型的表示一个名为“A”的张量：A。 我们通过写入Ai，j，k来识别坐标（i，j，k）处的A的元素。


One important operation on matrices is thetranspose. The transpose of amatrix is the mirror image of the matrix across a diagonal line, called themaindiagonal, running down and to the right, starting from its upper left corner. Seefigure 2.1 for a graphical depiction of this operation. We denote the transpose of amatrix A as $A^T$ and it is defined such that;<br>
矩阵的一个重要操作是处理。 阿姆斯特里克的转置是跨越对角线的矩阵的镜像，称为对角线，从左上角开始向右下移动。

$$A_{i,j} = A_{j,i}^T $$


In [22]:
spline = lambda : print("="*70)

import numpy as np

x = np.arange(8).reshape(2,4)
print(matrix)
spline()
xT = matrix.T
print(matrix_T)
spline()
sum = np.dot(x, xT)
print(sum)
spline()

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
[[ 14  38]
 [ 38 126]]


In [34]:
a = np.arange(4)

b = np.arange(4, 8)
print(b)
np.dot(a, b)


[4 5 6 7]


38


$$
C_{i,j} = \sum\limits_{k=1}A_{i,k}B_{k,j}
$$
$$
A(B + C) = AB + AC.
$$


In [50]:
# test
a = np.random.rand(3, 3)
b = np.random.rand(3, 3)
c = np.random.rand(3, 3)
spline()
d = b+c
p = np.dot(a,d)
print(p)
spline()
e, f = np.dot(a, b), np.dot(a, c)
q = e+f
print(q)
spline()
xy = p * q
yx = np.dot(p, q)
print(xy)
spline()
print(yx)
z = np.dot(q, p)
spline()
print(z)

[[ 2.48865238  1.78969825  1.47758898]
 [ 1.0045247   0.49750194  0.59189771]
 [ 1.45619703  0.66809565  0.84150039]]
[[ 2.48865238  1.78969825  1.47758898]
 [ 1.0045247   0.49750194  0.59189771]
 [ 1.45619703  0.66809565  0.84150039]]
[[ 6.19339067  3.20301981  2.18326919]
 [ 1.00906988  0.24750818  0.3503429 ]
 [ 2.1205098   0.4463518   0.7081229 ]]
[[ 10.14284746   6.33148591   5.97991532]
 [  3.86158547   2.44074856   2.27682704]
 [  5.52047717   3.50073491   3.25522787]]
[[ 10.14284746   6.33148591   5.97991532]
 [  3.86158547   2.44074856   2.27682704]
 [  5.52047717   3.50073491   3.25522787]]


In [72]:
a = np.repeat(1,4).reshape(2, 2)
print(a)
# a1 = np.linalg.eigvals(a)
# a1
# print(a1)
# spline()
# t = np.dot(a, a1)
# print(t)
# spline()

# ### a2 为矩阵a的特征值, a3为矩阵a的特征向量
# a2, a3 = np.linalg.eig(a)
# print(a2)
# spline()
# print(a3)

#### 逆矩阵 ---并不是所有的矩阵都有逆矩阵

# inverse_a = np.linalg.inv(a)
# spline()
# product = np.dot(a, a.T)
# print(np.linalg.inv(product))



[[1 1]
 [1 1]]


In [82]:
A = np.matrix([[1, 2, 3, 4],
              [5, 5, 6, 8],
              [7, 9, 9, 1],
              [4, 6, 7, 1]])
# product = np.dot(a,a)
# print(product)
# spline()
#### A的逆矩阵
# inverseA = A.I
# print(inverseA)
# ### A的单元矩阵 所谓的单元矩阵就是 该矩阵乘以单元矩阵还是该矩阵
# identiyA = np.dot(inverseA, A)
# print(identiyA)

# ji = np.dot(identiyA, A)
# spline()
# print(ji)
# i = np.linalg.det(A)
# spline()
# print(i)

norm = np.linalg.norm(A)
print(norm)

22.2261107709
